services:
  webhook:
    build:
      context: /root/binotel_gdrive/api/
      dockerfile: Dockerfile
    container_name: webhook
    volumes:
      - /root/binotel_gdrive/api/:/app:ro
    networks:
      - main_net
    deploy:
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /root/binotel_gdrive/nginx/sslcerts:/etc/nginx/sslcerts:ro
      - /root/binotel_gdrive/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - main_net
    deploy:
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  main_net:
    driver: bridge